# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebc300e7b218382912f208e573b297c46e532adffa05d1b388aa615c8a740e62f32a22dec9d423a4489deb7da843ce1eb55d87295c10b28a4be3cfb6becdfc96

test:
  secret_key_base: 1abfa8b5422f9ec795403e9de24a8060811020d31b89d43409e54b04a7182033ca1d815f5a6bba41461e2d87555298c16597172846c7788d4920a5a5d495323e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
